#!/bin/bash

#mpv arguments
mpvargs="--hwdec no --fs"

#Video formats to be pulled by youtube-dl
mpvquality="--ytdl-format=bestvideo[ext=mp4]+bestaudio[ext=m4a]"

#Create file to store last URL
touch /tmp/videourl

function loop(){
	#Sleep to prevent while loop spam
	sleep 2
	#Store the current selection
	url=`xclip -selection clipboard -o` 
	if [[ $url == "$(cat /tmp/videourl)" ]]; then return; fi
	case "$url" in
		*youtube*) play "$url" $mpvquality ;;
		*youtu.be*) play "$url" $mpvquality ;;
		*vimeo*) play "$url";;
		*twitch*) play "$url" ;;
		*.cc.com*) play "$url" ;;
		*ted.com*) play "$url" ;;
		*) return ;;
	esac
}

play() {
	#If above is true then store the new URL to the file
	echo "$url" > /tmp/videourl
	#Play the video
	mpv $mpvargs $2 "$1"
}

#Loop until Ctrl-C
while(true)
do
	loop
done
